-- Employee Table
CREATE TABLE EMPLOYEE( 
EmployeeID INT PRIMARY KEY, 
FIRSTNAME VARCHAR(50), 
LASTNAME VARCHAR(50), 
Department VARCHAR(50), 
SALARY DECIMAL(10, 2), 
HireDate DATE 

); 


-- read 
SELECT * FROM EMPLOYEE

--ROUND 
SELECT FIRSTNAME, ROUND(SALARY, -3) AS ROUNDEDSALARY FROM EMPLOYEE ; 

-- COUNT 
SELECT COUNT(*) AS TOTALAMOUNT FROM STUDETNS;  

-- MAX SALARY 
SELECT DEPARTMENT , MAX(SALARY) AS HighestSalary 
FROM EMPLOYEE
GROUP BY DEPARTMENT;  

-- CLAUSE BY 
SELECT 
     FIRSTNAME, 
	 DEPARTMENT, 
	 SALARY, 
	 AVG(SALARY) OVER() AS AVGSALARY -- calculate the avg of all rows 
FROM EMPLOYEE;  


-- [PARTITION  BY]
SELECT 
     FIRSTNAME, 
	 DEPARTMENT, 
	 SALARY, 
	 AVG(SALARY) OVER(PARTITION BY DEPARTMENT) AS DEPAVYSALARY -- calculate the avg of all rows 
FROM EMPLOYEE;  

-- RANKING BY 
SELECT 
     FIRSTNAME, 
	 DEPARTMENT, 
	 SALARY, 
	 ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROWNUM 
FROM EMPLOYEE;  

-- RANK BY 
SELECT 
     FIRSTNAME, 
	 DEPARTMENT, 
	 SALARY, 
	 RANK() OVER(ORDER BY SALARY DESC) AS RANKSALARY 
FROM EMPLOYEE;  

