-- Employee Table
CREATE TABLE EMPLOYEE( 
EmployeeID INT PRIMARY KEY, 
FIRSTNAME VARCHAR(50), 
LASTNAME VARCHAR(50), 
Department VARCHAR(50), 
SALARY DECIMAL(10, 2), 
HireDate DATE 

); 


-- read 
SELECT * FROM EMPLOYEE

--ROUND 
SELECT FIRSTNAME, ROUND(SALARY, -3) AS ROUNDEDSALARY FROM EMPLOYEE ; 

-- COUNT 
SELECT COUNT(*) AS TOTALAMOUNT FROM STUDETNS;  

-- MAX SALARY 
SELECT DEPARTMENT , MAX(SALARY) AS HighestSalary 
FROM EMPLOYEE
GROUP BY DEPARTMENT;